services:
  oculus-backend:
    build: ./backend
    container_name: oculus_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - data_volume:/data
    env_file:
      - backend/.env
    depends_on:
      - redis
      - mongo
      - gjtiff

  celery-worker:
    container_name: oculus_celery-worker
    build: ./backend
    command: celery -A app.infrastructure.celery.celery_app.celery worker -l info
    volumes:
      - data_volume:/data
    env_file:
      - backend/.env
    depends_on:
      - redis
      - mongo
    restart: always

  celery-worker-processing:
    build: ./backend
    container_name: oculus_celery-worker-processing
    command: celery -A app.infrastructure.celery.celery_app.celery worker -Q process_task_queue --concurrency=1 -l info
    volumes:
      - data_volume:/data
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - backend/.env
    depends_on:
      - redis
      - mongo
    restart: always

  celery-beat:
    build: ./backend
    container_name: oculus_celery-beat
    command: celery -A app.infrastructure.celery.celery_app.celery beat --loglevel=info
    volumes:
      - data_volume:/data
    depends_on:
      - redis
      - mongo
    env_file:
      - backend/.env
    restart: always

  redis:
    image: redis:7
    container_name: oculus_redis
    ports:
      - "6379:6379"
    restart: always

  mongo:
    image: mongo:6
    container_name: oculus_mongo
    ports:
      - "27017:27017"
    command: --quiet
    restart: always

  gjtiff:
    build: ./gjtiff
    container_name: oculus_gjtiff # !!! This container must be named 'oculus_gjtiff' as GJTIFFProcessor Python class is hardcoded to this name !!!
    command: [ "sleep", "infinity" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    volumes:
      - ./gjtiff:/gjtiff
      - data_volume:/data

  oculus-nginx:
    build: ./frontend
    container_name: oculus_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/oculus.cesnet.cz/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/oculus.cesnet.cz/privkey.pem:/etc/ssl/private/privkey.pem:ro
      - data_volume:/data:ro
    env_file:
      - frontend/.env
    depends_on:
      - oculus-backend
    restart: always

volumes:
  data_volume:
