from enum import Enum


class JobStatus(str, Enum):
    ACCEPTED = "ACCEPTED"
    DOWNLOADING = "DOWNLOADING"
    DOWNLOADING_COMPLETE = "DOWNLOAD_COMPLETE"
    DOWNLOADING_FAILED = "DOWNLOAD_FAILED"
    PROCESSING = "PROCESSING"
    PROCESSING_COMPLETE = "PROCESSING_COMPLETE"
    PROCESSING_FAILED = "PROCESSING_FAILED"
    FINALIZING = "FINALIZING"
    FINALIZING_FAILED = "FINALIZING_FAILED"
    FINISHED = "FINISHED"
    FAILED = "FAILED"
