# nginx init certificate generation - http setup only
# This configuration is nescessary for creating first Let's encrypt certificate
# Must be provided in frontend/Dockerfile for the first time (commented line)
# After succesful LE cert generation, just swap comments in Dockerfile COPY command lines

server {
    listen 80;
    server_name oculus.cesnet.cz;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
